import { Poppins } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700" , "900", "800", "600", "500", "300"],
});

export const metadata = {
  title: "First Nextjs App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased`}
      >
        <nav className="bg-gray-800 text-white p-4">
          <ul className="flex space-x-4">
            <li><Link href="/"> Home </Link></li>
            <li><Link href="/about"> About</Link></li>
            <li><Link href="/blogs"> Blogs</Link></li>
          </ul>
        </nav>
        <div className="p-4">{children}</div>
      </body>
    </html>
  );
}
